version: '3.8'

# ----------------------------------------------------
# X-Template for Application Services
# ----------------------------------------------------
x-base-app: &base-app
  restart: unless-stopped
  depends_on:
    redis_cache:
      condition: service_started
    kafka:
      condition: service_started

services:

  # ====================================================
  # 1. CORE INFRASTRUCTURE
  # ====================================================

  # -------------------------
  # Shared Redis Cache
  # -------------------------
  redis_cache:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data_cache:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10
      timeout: 5s

  # -------------------------
  # Shared Zookeeper for Kafka
  # -------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "bash", "-c", "echo srvr | nc localhost 2181 | grep Mode"]
      interval: 10s
      timeout: 5s
      retries: 5

  # -------------------------
  # Shared Kafka
  # -------------------------
  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD", "bash", "-c", "nc -z localhost 9092"]
      interval: 10s
      retries: 10
      timeout: 10s

  # -------------------------
  # Mailhog для тестирования почты
  # -------------------------
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"


  # ====================================================
  # 2. AUTHENTIFICATION SERVICE INFRA & APPS
  # ====================================================

  # -------------------------
  # Auth PostgreSQL
  # -------------------------
  auth_postgres:
    image: postgres:16
    container_name: auth_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - pg_data_auth:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  # -------------------------
  # Auth Service Main App
  # -------------------------
  auth_service:
    <<: *base-app
    build:
      context: ../../services/authentification/
    env_file:
      - ../../services/authentification/.env
    container_name: auth_service_dev
    ports:
      - "8000:8000"
    depends_on:
      auth_postgres:
        condition: service_healthy
    volumes:
      - ../../services/authentification:/app
      - geoip_data:/geoip
      - ../../services/authentification/certs:/app/certs
    command: >
      sh -c "
        echo 'Applying Alembic migrations...' && alembic upgrade head &&
        echo 'Starting server...' && gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 --forwarded-allow-ips '*' --access-logfile '-'
      "

  # -------------------------
  # Auth Arq worker
  # -------------------------
  auth_worker:
    <<: *base-app
    build:
      context: ../../services/authentification/
    env_file:
      - ../../services/authentification/.env
    container_name: auth_worker_dev
    depends_on:
      - auth_service
      - auth_postgres
    volumes:
      - ../../services/authentification:/app
      - geoip_data:/geoip
      - ../../services/authentification/certs:/app/certs
    command: bash /app/wait-for-kafka.sh kafka 9092 arq app.worker.WorkerSettings


  # ====================================================
  # 3. CLASSIFICATION SERVICE INFRA & APPS
  # ====================================================

  # -------------------------
  # Classification PostgreSQL
  # -------------------------
  class_postgres:
    image: postgres:16
    container_name: class_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: class_db
    ports:
      - "5434:5432"
    volumes:
      - pg_data_class:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  # -------------------------
  # Categorization Service Main App
  # -------------------------
  categorization_service:
    <<: *base-app
    build:
      context: ../../services/classification/
    env_file:
      - ../../services/classification/.env
    container_name: class_service_dev
    ports:
      - "8001:8001"
    depends_on:
      class_postgres:
        condition: service_healthy
    volumes:
      - ../../services/classification:/app
      - models_data:/models
      - datasets_data:/app/datasets
    command: >
      sh -c "
        echo 'Waiting for Kafka...' &&
        bash /app/wait-for-kafka.sh kafka 9092 &&
        echo 'Applying Alembic migrations...' && alembic upgrade head &&
        echo 'Starting server...' &&
        gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8001
      "

  # -------------------------
  # Arq worker
  # -------------------------
  categorization_worker:
    <<: *base-app
    build:
      context: ../../services/classification/
    env_file:
      - ../../services/classification/.env
    container_name: class_worker_dev
    depends_on:
      - categorization_service
      - class_postgres
    volumes:
      - ../../services/classification:/app
      - models_data:/models
      - datasets_data:/app/datasets
    command: bash /app/wait-for-kafka.sh kafka 9092 arq app.worker.WorkerSettings

  # -------------------------
  # Kafka Consumers
  # -------------------------
  categorization_consumers:
    <<: *base-app
    build:
      context: ../../services/classification/
    env_file:
      - ../../services/classification/.env
    container_name: class_consumers_dev
    depends_on:
      - categorization_service
      - class_postgres
    volumes:
      - ../../services/classification:/app
      - models_data:/models
      - datasets_data:/app/datasets
    command: bash /app/wait-for-kafka.sh kafka 9092 python run_consumers.py

# ====================================================
# 4. VOLUMES
# ====================================================
volumes:
  # Auth Service
  pg_data_auth:
  pg_data_auth_test:
  geoip_data: {}
  
  # Classification Service
  pg_data_class:
  models_data:
  datasets_data:

  redis_data_cache: