version: '3.8'

services:
  api_gateway:
    image: nginx:alpine
    container_name: api_gateway
    ports:
      - "80:80"
    volumes:
      - ./../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      auth_service:
        condition: service_healthy
      # class_service:
      #   condition: service_healthy
      goals_service:
        condition: service_healthy
    networks:
      - smartbudget-net

  redis_cache:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data_cache:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10
      timeout: 5s
    restart: unless-stopped
    networks:
      - smartbudget-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    env_file:
      - ../../infra/.env
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME}
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z localhost 2181 || exit 1"]
      interval: 5s
      retries: 5
      timeout: 2s
    restart: unless-stopped
    networks:
      - smartbudget-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    env_file:
      - ../../infra/.env
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: ${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR}
      ALLOW_PLAINTEXT_LISTENER: ${ALLOW_PLAINTEXT_LISTENER}
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092"]
      interval: 10s
      retries: 10
      timeout: 3s
    restart: unless-stopped
    networks:
      - smartbudget-net

  auth_postgres:
    image: postgres:16
    container_name: auth_postgres
    environment:
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pg_data_auth:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 10
      timeout: 5s
    networks:
      - smartbudget-net

  auth_service:
    build:
      context: ../../services/authentification/
    env_file:
      - ../../services/authentification/.env
    container_name: auth_service
    ports:
      - "8000:8000"
    depends_on:
      auth_postgres:
        condition: service_healthy
      redis_cache:
        condition: service_healthy
      kafka:
        condition: service_healthy
    volumes:
      - ../../services/authentification:/app
      - geoip_data:/geoip
      - ../../services/authentification/certs:/app/certs
    restart: unless-stopped
    command: >
      sh -c "
        alembic upgrade head &&
        gunicorn app.main:app -w 1 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/auth/health"]
      interval: 10s
      retries: 3
      timeout: 5s
    networks:
      - smartbudget-net

  auth_worker:
    build:
      context: ../../services/authentification/
    env_file:
      - ../../services/authentification/.env
    container_name: auth_worker
    depends_on:
      auth_service:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis_cache:
        condition: service_healthy
    volumes:
      - ../../services/authentification:/app
      - geoip_data:/geoip
      - ../../services/authentification/certs:/app/certs
    command: arq app.worker.WorkerSettings
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "find /tmp/healthy -mmin -1 | grep -q ."]
      interval: 20s
      retries: 3
    networks:
      - smartbudget-net

  # class_postgres:
  #   image: postgres:16
  #   container_name: class_postgres
  #   environment:
  #     POSTGRES_USER: ${CLASS_POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${CLASS_POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${CLASS_POSTGRES_DB}
  #   ports:
  #     - "5434:5432"
  #   volumes:
  #     - pg_data_class:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 5s
  #     retries: 10
  #     timeout: 5s
  #   networks:
  #     - smartbudget-net

  # class_service:
  #   build:
  #     context: ../../services/classification/
  #   env_file:
  #     - ../../services/classification/.env
  #   container_name: class_service
  #   ports:
  #     - "8001:8000"
  #   depends_on:
  #     class_postgres:
  #       condition: service_healthy
  #     redis_cache:
  #       condition: service_healthy
  #     kafka:
  #       condition: service_healthy
  #   volumes:
  #     - ../../services/classification:/app
  #     - models_data:/models
  #     - datasets_data:/app/datasets
  #   command: >
  #     sh -c "
  #       alembic upgrade head &&
  #       gunicorn app.main:app -w 1 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000
  #     "
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/class/health"]
  #     interval: 10s
  #     retries: 3
  #     start_period: 30s
  #   networks:
  #     - smartbudget-net

  # class_worker:
  #   build:
  #     context: ../../services/classification/
  #   env_file:
  #     - ../../services/classification/.env
  #   container_name: class_worker
  #   depends_on:
  #     class_service:
  #       condition: service_healthy
  #     kafka:
  #       condition: service_healthy
  #     redis_cache:
  #       condition: service_healthy
  #   volumes:
  #     - ../../services/classification:/app
  #     - models_data:/models
  #     - datasets_data:/app/datasets
  #   command: arq app.worker.WorkerSettings
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "sh", "-c", "find /tmp/healthy -mmin -1 | grep -q ."]
  #     interval: 30s
  #     retries: 3
  #     start_period: 30s
  #   networks:
  #     - smartbudget-net

  # class_consumers:
  #   build:
  #     context: ../../services/classification/
  #   env_file:
  #     - ../../services/classification/.env
  #   container_name: class_consumers
  #   depends_on:
  #     class_service:
  #       condition: service_healthy
  #     kafka:
  #       condition: service_healthy
  #     redis_cache:
  #       condition: service_healthy
  #   volumes:
  #     - ../../services/classification:/app
  #     - models_data:/models
  #     - datasets_data:/app/datasets
  #   command: python run_consumers.py
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "sh", "-c", "find /tmp/healthy -mmin -1 | grep -q ."]
  #     interval: 30s
  #     retries: 3
  #     start_period: 30s
  #   networks:
  #     - smartbudget-net

  transactions_postgres:
    image: postgres:16
    container_name: transactions_postgres
    environment:
      POSTGRES_USER: ${TRANS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TRANS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TRANS_POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - pg_data_transactions:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 10
      timeout: 5s
    networks:
      - smartbudget-net

  transactions:
    build:
      context: ../../services/transactions/SmartBudget.transactions/
      dockerfile: Dockerfile
    container_name: transactions
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      DATABASE_DSN: ${DATABASE_DSN}
      KAFKA_BOOTSTRAP_SERVERS: ${TRANSACTION_KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_GROUP_ID: ${KAFKA_GROUP_ID}
      USERS_ACTIVE_TOPIC: ${USERS_ACTIVE_TOPIC}
      TRANSACTION_CLASSIFIED_TOPIC: ${TRANSACTION_CLASSIFIED_TOPIC}
      BANK_POLL_INTERVAL: ${BANK_POLL_INTERVAL}
    ports:
      - "8082:8080"
    depends_on:
      transactions_postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - smartbudget-net

  goals_postgres:
    image: postgres:16
    env_file:
      - ../../infra/.env
    container_name: goals_postgres
    environment:
      POSTGRES_USER: ${GOALS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${GOALS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${GOALS_POSTGRES_DB}
    ports:
      - "5436:5432"
    volumes:
      - pg_data_goals:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 10
      timeout: 5s
    networks:
      - smartbudget-net

  goals_service:
    build:
      context: ../../services/goals/
    env_file:
      - ../../services/goals/.env
    container_name: goals_service
    ports:
      - "8002:8000"
    depends_on:
      goals_postgres:
        condition: service_healthy
      redis_cache:
        condition: service_healthy
      kafka:
        condition: service_healthy
    volumes:
      - ../../services/goals:/app
    restart: unless-stopped
    command: >
      sh -c "
        alembic upgrade head &&
        gunicorn app.main:app -w 1 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/goals/health"]
      interval: 10s
      retries: 3
      timeout: 5s
    networks:
      - smartbudget-net

  goals_worker:
    build:
      context: ../../services/goals/
    env_file:
      - ../../services/goals/.env
    container_name: goals_worker
    depends_on:
      goals_service:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis_cache:
        condition: service_healthy
    volumes:
      - ../../services/goals:/app
    command: arq app.worker.WorkerSettings
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "find /tmp/healthy -mmin -1 | grep -q ."]
      interval: 20s
      retries: 3
    networks:
      - smartbudget-net

  goals_consumer:
    build:
      context: ../../services/goals/
    env_file:
      - ../../services/goals/.env
    container_name: goals_consumer
    depends_on:
      goals_service:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis_cache:
        condition: service_healthy
    volumes:
      - ../../services/goals:/app
    command: python run_consumer.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "find /tmp/healthy -mmin -1 | grep -q ."]
      interval: 20s
      retries: 3
    networks:
      - smartbudget-net

volumes:
  pg_data_auth:
  # pg_data_class:
  pg_data_goals:
  pg_data_transactions:
  geoip_data:
  models_data:
  datasets_data:
  redis_data_cache:
  kafka_data:

networks:
  smartbudget-net:
    name: smartbudget-net