version: '3.8'

services:

  redis_cache:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data_cache:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10
      timeout: 5s
    restart: unless-stopped
    networks:
      - smartbudget-net

  auth_zookeeper_dev:
    image: confluentinc/cp-zookeeper:7.5.0
    env_file:
      - ../../infra/.env
    container_name: auth_zookeeper_dev
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME}
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z localhost 2181 || exit 1"]
      interval: 5s
      retries: 10
      timeout: 5s
    restart: unless-stopped
    networks:
      - smartbudget-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    env_file:
      - ../../infra/.env
    container_name: kafka
    depends_on:
      auth_zookeeper_dev:
        condition: service_healthy
    environment:
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: ${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR}
      ALLOW_PLAINTEXT_LISTENER: ${ALLOW_PLAINTEXT_LISTENER}
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 10s
      retries: 10
      timeout: 3s
    restart: unless-stopped
    networks:
      - smartbudget-net

  class_postgres:
    image: postgres:16
    container_name: class_postgres
    environment:
      POSTGRES_USER: ${CLASS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CLASS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${CLASS_POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - pg_data_class:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 10
      timeout: 5s
    networks:
      - smartbudget-net

  categorization_service:
    build:
      context: ../../services/classification/
    env_file:
      - ../../services/classification/.env
    container_name: class_service_dev
    ports:
      - "8001:8001"
    depends_on:
      class_postgres:
        condition: service_healthy
      redis_cache:
        condition: service_healthy
      kafka:
        condition: service_healthy
    volumes:
      - ../../services/classification:/app
      - models_data:/models
      - datasets_data:/app/datasets
    command: >
      sh -c "
        alembic upgrade head &&
        gunicorn app.main:app -w 1 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8001
      "
    restart: unless-stopped
    networks:
      - smartbudget-net

  categorization_worker:
    build:
      context: ../../services/classification/
    env_file:
      - ../../services/classification/.env
    container_name: class_worker_dev
    depends_on:
      - categorization_service
      - kafka
      - redis_cache
    volumes:
      - ../../services/classification:/app
      - models_data:/models
      - datasets_data:/app/datasets
    command: arq app.worker.WorkerSettings
    restart: unless-stopped
    networks:
      - smartbudget-net

  categorization_consumers:
    build:
      context: ../../services/classification/
    env_file:
      - ../../services/classification/.env
    container_name: class_consumers_dev
    depends_on:
      - categorization_service
      - kafka
      - redis_cache
    volumes:
      - ../../services/classification:/app
      - models_data:/models
      - datasets_data:/app/datasets
    command: python run_consumers.py
    restart: unless-stopped
    networks:
      - smartbudget-net

volumes:
  pg_data_class:
  models_data:
  datasets_data:
  redis_data_cache:
  kafka_data:

networks:
  smartbudget-net:
    name: smartbudget-net